# Generated by Django 4.2.1 on 2023-05-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='season',
        ),
    ]
