# Generated by Django 4.2.1 on 2023-05-27 09:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('futbol_app', '0003_league_season'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
